[mix]

copy = [
    '.circleci/*',
    '**/static/**/*',
    '**/templates/**/*',
]

ignore = [
    '**/*.pyc',
    # Unused modules
    "{% if not features.Has('harvester') %}harvesters.py{% endif %}",
    "{% if not features.Has('theme') %}theme{% endif %}",
    "{% if not features.Has('views') %}views.py{% endif %}",
    "{% if not features.Has('metrics') %}metrics.py{% endif %}",
    "{% if not features.Has('models') %}models.py{% endif %}",
    "{% if not features.Has('linkchecker') %}linkchecker.py{% endif %}",
    "{% if not features.Has('tasks') %}tasks.py{% endif %}",
    "{% if not features.Has('preview') %}preview.py{% endif %}",
    # Unused tests
    '{% if not features.Has("harvester") %}test_{{ identifier | replace("-", "_") }}_backend.py{% endif %}',
    '{% if not features.Has("views") %}test_{{ identifier | replace("-", "_") }}_views.py{% endif %}',
    '{% if not features.Has("preview") %}test_{{ identifier | replace("-", "_") }}_preview.py{% endif %}',
]

[[params]]
key = 'project_name'
label = 'Project name'
type = 'string'
default = 'My Plugin'

[[params]]
key = 'project_slug'
label = "Slug"
type = 'string'
prompt = "Project slug ?"
default = 'udata-{{ project_name | replace(" ", "-") | lower }}'

[[params]]
key = 'license'
label = "License"
type = 'string'
choices = ["AGPL", "MIT"]
prompt = "Under which license the plugin will be published ?"
default = "AGPL"

[[params]]
key = 'pypackage'
label = "Python package"
prompt = "What's the root Python package name ?"
default = '{{ project_slug | replace("-", "_") }}'

[[params]]
key = 'identifier'
label = "Plugin identifier"
type = 'string'
default = '{{ project_slug | replace("udata-", "") }}'

[[params]]
key = 'author'
default = "Open Data Team"

[[params]]
key = 'email'
default =  "contact@opendata.team"

[[params]]
key = 'description'
default = "My awesome uData plugin"

[[params]]
key = 'version'
default =  "0.1.0.dev"

[[params]]
key = 'website'
default = "https://github.com/opendatateam/{{ project_slug }}"

[[params]]
key = 'features'
type = 'set'
prompt = "Which features do you want to expose ?"
choices = ["harvester", "theme", "views", "metrics", "models", "linkchecker", "tasks", "preview", "generic"]

